CREATE TABLE IF NOT EXISTS Users (
    user_id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(40) NOT NULL UNIQUE,
    email VARCHAR(320) NOT NULL UNIQUE,
    password VARCHAR(40) NOT NULL,
    salt VARCHAR(8) NOT NULL
);

CREATE TABLE IF NOT EXISTS Notes (
    note_id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INT,
    content VARCHAR(1024),
    FOREIGN KEY (user_id) REFERENCES User(user_id)
);